In [2]:
import dash_html_components as html
import dash_core_components as dcc
from dash.dependencies import Input, Output
import plotly.graph_objects as go
import pandas as pd
import altair as alt

/var/folders/nd/7w4xcjd90kq8t3xqbcklp8gm0000gn/T/ipykernel_41806/3153668486.py:1: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
/var/folders/nd/7w4xcjd90kq8t3xqbcklp8gm0000gn/T/ipykernel_41806/3153668486.py:2: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc

In [23]:
def displayCompare(countries, indicator):
        sheetName = indicator+' Proportion (Model)'
        df_tol =pd.DataFrame()
        for country in countries:
            temp = pd.read_excel("../data/mul_sum.xlsx",sheet_name=sheetName)
            temp = temp[(temp["Country and areas"] == country) & (temp['Estimate'].isin(['Point Estimate','Lower Uncertainty Bound','Upper Uncertainty Bound']))].iloc[:, -23:].T
            temp.columns = ['Point Estimate','Lower Uncertainty Bound','Upper Uncertainty Bound']
            temp['Year'] = temp.index
            temp.reset_index(drop=True, inplace=True)
            temp['Country'] = country
            df_tol = pd.concat([df_tol, temp], ignore_index=True)
        # df_tol['Estimate'].replace('-', np.nan, inplace=True)
        # df_tol['Estimate'].fillna(10, inplace=True)
        df_tol['Year'] = pd.to_datetime(df_tol['Year'], format='%Y')
        df_tol['Point Estimate'] = pd.to_numeric(df_tol['Point Estimate'], errors='coerce')
        df_tol['Lower Uncertainty Bound'] = pd.to_numeric(df_tol['Lower Uncertainty Bound'], errors='coerce')
        df_tol['Upper Uncertainty Bound'] = pd.to_numeric(df_tol['Upper Uncertainty Bound'], errors='coerce')

        points = alt.Chart(df_tol).mark_point(size = 4).encode(
            x='Year',
            y='Point Estimate',
            color='Country',
            tooltip=['Year', 'Point Estimate', 'Lower Uncertainty Bound', 'Upper Uncertainty Bound', 'Country']

            # tooltip=['Year', 'Estimate', 'Country'] 
        )
        return points

In [72]:
def deathNumberDisplay(country):
    df0 = pd.read_csv("../data/death_infant.csv")
    df0 = df0[df0["Country Name"]==country].iloc[:, -63:].T
    df0.columns = ["Death Number"]
    df0["Range"] ="Infant"
    df0['Year'] = df0.index
    df0.reset_index(drop=True, inplace=True)
    df0['Country'] = country

    df1 = pd.read_csv("../data/death_under_5.csv")
    df1 = df1[df1["Country Name"]==country].iloc[:, -63:].T
    df1.columns = ["Death Number"]
    df1["Range"] ="Under 5"
    df1['Year'] = df1.index
    df1.reset_index(drop=True, inplace=True)
    df1['Country'] = country

    df2 = pd.read_csv("../data/death_5-9.csv")
    df2 = df2[df2["Country Name"]==country].iloc[:, -63:].T
    df2.columns = ["Death Number"]
    df2["Range"] ="5-9"
    df2['Year'] = df2.index
    df2.reset_index(drop=True, inplace=True)
    df2['Country'] = country

    df3 = pd.read_csv("../data/death_10-14.csv")
    df3 = df3[df3["Country Name"]==country].iloc[:, -63:].T
    df3.columns = ["Death Number"]
    df3["Range"] ="10-14"
    df3['Year'] = df3.index
    df3.reset_index(drop=True, inplace=True)
    df3['Country'] = country

    df4 = pd.read_csv("../data/death_15-19.csv")
    df4 = df4[df4["Country Name"]==country].iloc[:, -63:].T
    df4.columns = ["Death Number"]
    df4["Range"] ="16-19"
    df4['Year'] = df4.index
    df4.reset_index(drop=True, inplace=True)
    df4['Country'] = country

    sum = pd.concat([df0,df1,df2,df3,df4])
    sum['Year']=pd.to_datetime(sum['Year'], format='%Y') 
    sum_2000_2021 = sum.query("Year > 1999 and Year <2022")
    chart = alt.Chart(sum_2000_2021).mark_bar().encode(
        alt.X("Year"),
        alt.Y("Death Number"),
        color="Range",
        tooltip=["Year","Death Number","Range"]
    )  
    return chart
deathNumberDisplay("China")

alt.Chart(...)

In [63]:
ok = deathNumberDisplay("Afghanistan")
ok['Year'] = pd.to_datetime(ok['Year'], format='%Y') 
fine = ok.query("Year > 1999 and Year <2022")

In [54]:
df = pd.read_csv("../data/death_under_5.csv")
df1 = df[df["Country Name"]=='Afghanistan'].iloc[:, -63:].T
df1.columns = ["Death Number"]
df1["Range"] ="Under 5"
df1['Year'] = df1.index
df1.reset_index(drop=True, inplace=True)
df1['Country'] = "Afghanistan"
df1

    Death Number    Range  Year      Country
0            NaN  Under 5  1960  Afghanistan
1            NaN  Under 5  1961  Afghanistan
2            NaN  Under 5  1962  Afghanistan
3            NaN  Under 5  1963  Afghanistan
4            NaN  Under 5  1964  Afghanistan
..           ...      ...   ...          ...
58       82306.0  Under 5  2018  Afghanistan
59       80677.0  Under 5  2019  Afghanistan
60       79117.0  Under 5  2020  Afghanistan
61       77811.0  Under 5  2021  Afghanistan
62           NaN  Under 5  2022  Afghanistan

[63 rows x 4 columns]

In [55]:
df2 = pd.read_csv("../data/death_5-9.csv")
df2 = df2[df2["Country Name"]=='Afghanistan'].iloc[:, -63:].T
df2.columns = ["Death Number"]
df2["Range"] ="5-9"
df2['Year'] = df2.index
df2.reset_index(drop=True, inplace=True)
df2['Country'] = "Afghanistan"
df2

    Death Number Range  Year      Country
0            NaN   5-9  1960  Afghanistan
1            NaN   5-9  1961  Afghanistan
2            NaN   5-9  1962  Afghanistan
3            NaN   5-9  1963  Afghanistan
4            NaN   5-9  1964  Afghanistan
..           ...   ...   ...          ...
58        2842.0   5-9  2018  Afghanistan
59        2751.0   5-9  2019  Afghanistan
60        2678.0   5-9  2020  Afghanistan
61        2619.0   5-9  2021  Afghanistan
62           NaN   5-9  2022  Afghanistan

[63 rows x 4 columns]

In [57]:
merge_df = pd.concat([df1,df2])
merge_df

    Death Number    Range  Year      Country
0            NaN  Under 5  1960  Afghanistan
1            NaN  Under 5  1961  Afghanistan
2            NaN  Under 5  1962  Afghanistan
3            NaN  Under 5  1963  Afghanistan
4            NaN  Under 5  1964  Afghanistan
..           ...      ...   ...          ...
58        2842.0      5-9  2018  Afghanistan
59        2751.0      5-9  2019  Afghanistan
60        2678.0      5-9  2020  Afghanistan
61        2619.0      5-9  2021  Afghanistan
62           NaN      5-9  2022  Afghanistan

[126 rows x 4 columns]

In [64]:
alt.Chart(fine).mark_bar().encode(
    alt.X("Year"),
    alt.Y("Death Number"),
    color="Range"
)

alt.Chart(...)